### ISSUE TITLE
`GTK::Clipboard.text does not support retrieval` in 33-clipboard.t

### ISSUE THREAD

**Issue by Altai-man** [Xliff/p6-GtkPlus#19]
Everything seem to work nicely: copy/paste by explicit buttons and hotkeys too, but when clicking on `Copy` button I see this:
```
GTK::Clipboard.text does not support retrieval
  in block  at /home/koto/Devel/p6-GtkPlus/lib/GTK/Clipboard.pm6 (GTK::Clipboard) line 76
GTK::Clipboard.text does not support retrieval
  in block  at /home/koto/Devel/p6-GtkPlus/lib/GTK/Clipboard.pm6 (GTK::Clipboard) line 76
```
and every click adds those again.

**Comment by Xliff** [comment]
This is due to some internals. These messages have been moved behind a debug flag. 

Thanks for reporting!
