### ISSUE TITLE
Add New Window

### ISSUE THREAD

**Issue by hythm7** [Xliff/p6-GtkPlus#22]
Getting this error when trying to add new window to application:

> (moar:3904): Gtk-CRITICAL **: 19:32:53.365: gtk_application_add_window: assertion 'GTK_IS_WINDOW (window)' failed

Code:
```
use GTK::Application;
use GTK::Window;
use GTK::Box;
use GTK::Button;

my $app = GTK::Application.new(
  title  => 'org.genex.test.widget',
  width  => 400,
  height => 400
);

my GTK::Button $new-win .= new_with_label: <new-win>;

$new-win.clicked.tap: { new-win };

$app.activate.tap({
my $box = GTK::Box.new-vbox(6);

$box.pack_start($new-win, False, True, 0);

$app.window.add: $box;
$app.show_all;
});

$app.run;

sub new-win () {
	my GTK::Window $window .= new: :title<NewWin>;
	$window.show;
	$app.add_window: $window;
}

```

**Comment by Xliff** [comment]
Ooh! That was interesting. Your major problem stemmed from the fact that you were using GTK::Window.new improperly. This meant that it went to the default constructor, which didn't do the right thing. This won't be much of an issue, but I have noted that the default constructor should be inhibited for all widget-based objects. That will be a job for the future, however.

I did manage to get your example to work, however. Here is the adjusted code:

```perl6
use v6.c;

use GTK::Application;
use GTK::Window;
use GTK::Box;
use GTK::Button;
use GTK::Raw::Types;

my $app = GTK::Application.new(
  title  => 'org.genex.test.widget',
  width  => 400,
  height => 400
);

sub new-win () {
	my $window = GTK::Window.new( GTK_WINDOW_TOPLEVEL, :title<NewWin> );
	$window.show;
	$app.add_window: $window;
}

$app.activate.tap({
  my $box = GTK::Box.new-vbox(6);
  my GTK::Button $new-win .= new_with_label: <new-win>;

  $new-win.clicked.tap: { new-win };
  $box.pack_start($new-win, False, True, 0);

  $app.window.destroy-signal.tap: { $app.exit };

  $app.window.add: $box;
  $app.show_all;
});

$app.run;
```

I've also added this small code to the test suite, as I did not have an example for creating new windows.

Thanks for testing!

**Comment by hythm7** [comment]
Thank you.
