### ISSUE TITLE
FileChooserButton

### ISSUE THREAD

**Issue by hythm7** [Xliff/p6-GtkPlus#23]
File Chooser Button doesn't show in window;

Code: 

```
use GTK::Application;
use GTK::Box;
use GTK::Button;
use GTK::FileChooserButton;

my $app = GTK::Application.new(
  title  => 'org.genex.test.widget',
  width  => 400,
  height => 400
);

my GTK::Button $exit .= new_with_label: <exit>;
my GTK::FileChooserButton $chooser .= new;

$exit.clicked.tap: { $app.exit  };

## What is the correct syntax for getting the filename once selected?
# $chooser.select_file.tap: { say $chooser.filename };

$app.activate.tap({
my $box = GTK::Box.new-vbox(6);

$box.pack_start($chooser, False, True, 0);
$box.pack_start($exit, False, True, 0);

$app.window.add: $box;
$app.show_all;
});

$app.run;

```

**Comment by Xliff** [comment]
This is a similar issue as the last one. You were using GTK::FileChooser.new, which goes directly to Mu.new and doesn't initialize anything. I have added code to prevent this. Here is the corrected example:

```perl6
use v6.c;

use GTK::Application;
use GTK::Box;
use GTK::Button;
use GTK::FileChooserButton;
use GTK::Raw::Types;

my $app = GTK::Application.new(
  title  => 'org.genex.test.filechooser',
  width  => 400,
  height => 400
);

$app.activate.tap({
  # Should always do this.
  CATCH { default { .message.say; $app.exit } }

  my $box = GTK::Box.new-vbox(6);
  my $exit = GTK::Button.new_with_label: <exit>;
  my $chooser = GTK::FileChooserButton.new(
    'Pick a file', GTK_FILE_CHOOSER_ACTION_OPEN
  );

  $chooser.selection-changed.tap: {
    say "Selected: { $chooser.filename }"
  };

  $exit.clicked.tap: { $app.exit  };
  $app.window.destroy-signal.tap: { $app.exit };

  $box.pack_start($chooser, False, True, 0);
  $box.pack_start($exit, False, True, 0);
  $app.window.add($box);
  $app.window.show_all;
});

$app.run;
```

Just as a side note: it's always best to keep _all_ of your creation logic in the $app.activate.tap, unless you need something global. It's still better to make that container global and set it in $app.activate.tap, though, as in that block, you are _guaranteed_ to be running after gtk_init().

Further comments welcome, but I will close this issue. Please re-open if I've missed something.

**Comment by hythm7** [comment]
That worked great. Thanks for the explanation. noted.

**Comment by hythm7** [comment]
@Xliff keeping all creation logic in $app.activate.tap goes for all added windows as well, or only for the first $app.window?

I'm thinking of creating a "content" multi sub for the first window, and another multi sub for newly added windows.

Would something like that below example considered not good practice? https://github.com/hythm7/Z/blob/master/lib/Z/Util.pm#L19

**Comment by Xliff** [comment]
Nope! For dynamically created widgets, that rule does _not_ apply. It will probably help if you have some way to reference them, again. Creating them in a scope and then "losing" them in containers may lead to unexpected behavior. I usually keep a global hash for stuff like that, and add things to it, when they are created.

What you have in that bit of code looks fine enough. You are passing the created control back to the caller. It is then the caller's responsibility to handle them properly.
