### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by ccworld1000** [Xliff/p6-GtkPlus#3]
Some problems

Is there any part of the code generated automatically?

When will it be officially used?

**Comment by Xliff** [comment]
Yes, I use code generators, but none of that code is used without review. Each module goes through several phases of hand modification.

I do not have a time-frame for release, but more help is always welcome.

My basic condition for even considering a release will be 50% functionality across 50% of the GTK objects. Please feel free to raise issues and submit PRs.
