### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by ccworld1000** [Xliff/p6-GtkPlus#4]
is native('gtk-3') 

Change to variable

is native($libGTK3) 

Easy for global control

**Comment by Xliff** [comment]
Good idea. Will add that to the TODO. Thanks for the suggestion!

**Comment by ccworld1000** [comment]
I just submitted, you can check to see, there is no environment on my side.

**Comment by Xliff** [comment]
OK. I have made a slight change. If you can do that and commit, I will merge.

Thanks a lot!

**Comment by Xliff** [comment]
Merged and updated!
