### ISSUE TITLE
parallel build script

### ISSUE THREAD

**Issue by hythm7** [Xliff/p6-GtkPlus#42]
I made a slight modification to `build.sh` to build concurrently, which saved almost 1000 seconds:

I tested on a VM, here is the output:

```
build.sh:
real 4233.81
user 5207.20
sys 313.37

parallel-build.sh
real 3266.57
user 5228.40
sys 314.50
```

Since this is a VM, (and I don't trust VMs performance, I will test on a physical machine later when I get home ). 
can you check if that made any difference on your machine as well?

```
#!/bin/bash

if [ "$1" == "new" ]; then
  rm LastBuildResults*
else
  perl6 scripts/backup_results.pl6
fi
export P6_BUILDING_GTK=1
echo -e "Dependency Generation\n=====================" >> LastBuildResults
/usr/bin/time -p -o LastBuildResults -a perl6 scripts/dependencies.pl6
/usr/bin/time -p /bin/bash -c '(
cat BuildList | xargs -n1 -P$(nproc) -I{} ./p6gtkexec -e "say q[=== {} ===]; use {};" 2>&1
)' 2>&1 | tee -a LastBuildResults
unset P6_BUILDING_GTK
cp LastBuildResults stats/LastBuildResults-`date +%Y%m%d`

# Since this runs on parallel, the output will not be in order,
# for example printing === Module::Name === on the screen while it's actually compiling Another::Module
```
At first I tried to `use AllModules` in a single run instead of the `for` loop, to save `Raku` startup time with each iteration, but that did not work, I got an error after a few minutes.

**Comment by Xliff** [comment]
I just got home from work, but tl;dr... if we ever meet:

1) I will probably kiss you (or buy you a beer...)
2) I will need to see about getting it so the output can be collated for
statistics and reporting purposes. For that ALONE, I may not be able to use
this, as I am tracking full build times vs rakudo versions

I *really* appreciate this. Thanks so much for the effort!

- Xliff

**Comment by hythm7** [comment]
Beer would be good :) 

Makes sense. I see the importance of tracking build times.

no problem, all I did was couple lines change. it did not take anytime.

**Comment by Xliff** [comment]
Good work still needs to be recognized. :)
