### ISSUE TITLE
GTK::Application inheritance broke after 3f81ba63 commit

### ISSUE THREAD

**Issue by hythm7** [Xliff/p6-GtkPlus#44]
the below code worked fine for `3f81ba63` and previous commits, however it started to give this error after that commit:

```
Native call cast expected return type with CPointer, CStruct, CArray, or VMArray representation, but got a P6opaque (Nil)
  in sub nativecast at /home/hythm/.rakudobrew/versions/moar-blead/install/share/perl6/core/sources/947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall) line 694
  in sub cast at /home/hythm/dev/GTK/p6-GtkPlus/lib/GTK/Compat/Types.pm6 (GTK::Compat::Types) line 39
  in method roleInit-ActionMap at /home/hythm/dev/GTK/p6-GtkPlus/lib/GIO/Roles/ActionMap.pm6 (GIO::Roles::ActionMap) line 18
  in submethod BUILD at /home/hythm/dev/GTK/p6-GtkPlus/lib/GTK/Application.pm6 (GTK::Application) line 51
  in method new at /home/hythm/dev/GTK/p6-GtkPlus/lib/GTK/Application.pm6 (GTK::Application) line 149
  in block <unit> at <unknown file> line 1
```

code:
`use GTK::Application; class A is GTK::Application {}.new;`

**Comment by Xliff** [comment]
Thanks for the update. Been working on missing modules and must have missed a Nil sentinel. I will try and get to it Monday or Tuesday.

**Comment by Xliff** [comment]
@hythm - Be careful if you are overriding classes, most classes that are not prepared to be superclasses need a nil sentinel in their BUILD method. 

The basic fix looks like this: 

```perl6 
submethod BUILD (:$object) {
  return unless $object
  ...
}
```

Please note, that  fixing this will require checking _every_ module for this check. I am fixing them as I find them, though. If you wouldn't mind, if you see modules like this, could you attempt to fix and submit a PR? _[ x -- would be helpful, but not really the issue, as it turns out... see below ]_

Also note that your test code won't really do much, since it doesn't override BUILD with the proper initialization logic. Just an FYI.

Thanks!!

**Comment by Xliff** [comment]
Or not...

The part that is blowing up is that GTK::Application was _never intended to be subclassed_, and it also looks like my experimental role initialization code will not work in such cases. *sigh*

**Comment by Xliff** [comment]
@hythm OK. I think I have a workable fix in. This will more than likely be a long term fix until I have time to go over all of the new roles that use this type of initialization, so if you find more errors of this type, please note them here.

**Comment by hythm7** [comment]
Thanks Xliff. Will do.

**Comment by Xliff** [comment]
Just out of curiosity, did that fix work for you? I've done more of the not-so-long-term stuff in master so would like to know if It's going in the right direction.

**Comment by hythm7** [comment]
@Xliff, It worked for the particular test code above. but I in a different code I got similar error,  this time in `ApplicationWindow`. so I did the same fix you did for `Application` basically adding `is implementor` and `return unless $appwindow`. which fixed the error.

Then I forked the repo to submit that fix for ApplicationWindow,  saw you already added `is implementor` for all modules. however, I was not able to build the project because I'm getting the error below:

```
SORRY! Error while compiling /home/hythm/dev/GTK/p6-GtkPlus/lib/GTK/Bin.pm6 (GTK::Bin)
  Can't use unknown trait 'is' -> 'implementor' in an attribute declaration.
  at /home/hythm/dev/GTK/p6-GtkPlus/lib/GTK/Bin.pm6 (GTK::Bin):14
```

I removed `is implementor` from `GTK::Bin` and the error goes away. But I'm not sure if this is the right fix. so If you can point me to the right direction I can try to fix it and submit a PR.

**Comment by hythm7** [comment]
But yes I believe it's going in the right direction, because I didn't  see this issue anymore after your last commit. the only issue I'm seeing now is the mentioned `GTK::Bin` error above

**Comment by Xliff** [comment]
Thanks! I've pushed that fix along with other changes I am working on. Also, if you believe this has been handled, please close the issue. It can always be re-opened, if necessary.
