### ISSUE TITLE
 Version suggestion

### ISSUE THREAD

**Issue by ccworld1000** [Xliff/p6-GtkPlus#9]
META version GitHub tag version remains the same.

**Comment by Xliff** [comment]
Yes, and it will until it is ready to be released. I am thinking it is _almost_ close, however I am seriously concerned about the installation process. It takes a long time to precompile, and current zef does not provide the user with any feedback. When that is taken care of, I am very willing to release things as-is. Until then, I am willing to hold it. Interested folks can still download it and install, manually.
